language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy pytest pip
  - pip install -r requirements.txt

addons:
  postgresql: "9.3"

services:
  - redis-server

env:
  - SQL_DBNAME=ottomen SQL_USER=docker SQL_PASS=docker TRAVIS=true

before_script:
  - psql -c 'create database ottomen;' -U postgres
  - python manage.py db upgrade

notifications:
  slack: team-ottomen:E0PjYxU4NlXUfLF8i4zb0z99
  email: false

script:
  - py.test tests/resources