language: python
python:
  - "2.7"
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install -r requirements.txt
addons:
  postgresql: "9.3"
services:
  - redis-server
env:
  - SQL_DBNAME=ottomen SQL_USER=docker SQL_PASS=docker TRAVIS=true
before_script:
  - psql -c 'create database ottomen;' -U postgres
  - python manage.py db upgrade
notifications:
  slack: mechanicalturkteam:E0PjYxU4NlXUfLF8i4zb0z99
script: py.test -v