web:
  build: .
  command: gulp
  ports:
   - "5000:5004"
   - "3000:3000"
   - "3001:3001"
  expose:
    - "5000"
    - "3000"
    - "3001"
  volumes:
   - .:/code
  links:
   - redis
   - db:db
   - dbtest:dbtest

#nginx:
#  restart: always
#  build: ./docker/nginx/
#  ports:
#    - "80:80"
#  volumes:
#    - /www/static
#  volumes_from:
#    - web
#  links:
#    - web:web

redis:
  image: redis
  ports:
    - "5001:6379"

db:
  restart: always
  image: postgres:latest
  environment:
    POSTGRES_DB: ottomen
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker
  volumes:
    - ~/Projects/ottomen/migrations/db:/var/lib/postgresql
  ports:
    - "5002:5432"

dbtest:
  restart: always
  image: postgres:latest
  environment:
    POSTGRES_DB: ottomen
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker
  volumes:
    - ~/Projects/ottomen/migrations/db_test:/var/lib/postgresql
  ports:
    - "5003:5432"