# task
TASK_BATCH_SIZE = 10
TASK_NR_OF_BATCHES = 5
TASK_SIZE = 50
TASK_INITIAL_CONSENSUS = 30
TASK_RETURNING_CONSENSUS = 10
TASK_MINIMUM_MT_SCORE = .95
TASK_MINIMUM_MT_SUBMISSIONS = 500
TW_SET_SIZE = 20

# worker
WORKER_TW_POS = 1
WORKER_TW_NEG = 1
WORKER_CLASS_POS = 1
WORKER_CLASS_NEG = 1
MIN_TW_WORKER = 0.6


