"""empty message

Revision ID: 3626908291cc
Revises: 41efae71b0d5
Create Date: 2015-09-20 21:39:51.518966

"""

# revision identifiers, used by Alembic.
revision = '3626908291cc'
down_revision = '41efae71b0d5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('experiment_id', sa.Integer(), sa.ForeignKey('experiment.id'), nullable=True))
    op.alter_column('experiment', 'accuracy',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiment', 'accuracy',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('answer', 'experiment_id')
    ### end Alembic commands ###
