"""empty message

Revision ID: 41efae71b0d5
Revises: 47bd88c9d56e
Create Date: 2015-09-07 21:02:03.596835

"""

# revision identifiers, used by Alembic.
revision = '41efae71b0d5'
down_revision = '47bd88c9d56e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('worker_id', sa.String(), nullable=True))
    op.drop_column('session', 'turk_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('turk_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('session', 'worker_id')
    ### end Alembic commands ###
