"""empty message

Revision ID: 47bd88c9d56e
Revises: 1524fc2c8a7b
Create Date: 2015-09-06 13:52:56.694785

"""

# revision identifiers, used by Alembic.
revision = '47bd88c9d56e'
down_revision = '3626908291cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_column('accounts', 'username')
    ### end Alembic commands ###
