"""empty message

Revision ID: 4bfdc4a415b5
Revises: None
Create Date: 2015-08-31 11:25:35.488511

"""

# revision identifiers, used by Alembic.
revision = '4bfdc4a415b5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belief', sa.Boolean(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    ### end Alembic commands ###
